# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A-GXnsG11QOXkredZL1JZGMLwqLFu7rF
"""

import pandas as pd

"""## File Import

Here files has been imported from google drive using **upload()** function

google.colab package has been imported.
"""

from google.colab import files
uploades = files.upload()

from google.colab import drive
drive.mount("/content/drive")

data = pd.read_csv("/content/1. Weather Data (1).csv")
data

data.shape

data.index

data.columns

data.dtypes

data["Temp_C"].unique()

data.nunique()

data["Weather"].nunique()

data.count()

data["Rel Hum_%"].count()

data["Weather"].value_counts()

data.info()

data["Wind Speed_km/h"]

data["Wind Speed_km/h"].unique()

data["Weather"].value_counts()

"""# New Section

Q.1 List out the data where the weather is exaclty clear.

There are three methods for this.

1.   Filtering
2.   Group By
3.   


"""

# Method 1.
data[data.Weather=="Clear"]

# Method 2
data.groupby("Weather").get_group("Clear")

# Find out where the wind speed is exactly 4km/hr.
data[data['Wind Speed_km/h'] == 4]

# Finds out all the null values in a dataset.
data.isnull().sum()

# Find out all not null values in a dataset.
data.notnull().sum()

# Rename the column Weather, Temp_C to 'Weather Condition', 'Temerature'.
data.rename(columns = {'Weather' : 'Weather Condition', 'Temp_C' : 'Temerature'})

# Find out mean of all Visibility columns in a dataset.
data.Visibility_km.mean()

# Find out standard deviation of all Press_kPa columns in a dataset.
data.Press_kPa.std()

# Find out variance() of all Press_kPa columns in a dataset.
data.Press_kPa.var()

# Show all the columns where Weather conatins Snow.
data[data["Weather"].str.contains('Snow')]

# Show the list where WindSpeed > 24 && Visibility is exactly 25.
data[data['Wind Speed_km/h']>24].groupby("Visibility_km").get_group(25)

# Show the list where WindSpeed > 24 && Visibility is exactly 25.
data[(data['Wind Speed_km/h']>24) & (data['Visibility_km']==25)]

data.groupby("Weather").mean()

data.groupby("Weather").max()

data[data["Weather"]=="Fog"]

